/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import elecciones.FormacionPolitica;
import elecciones.Militante;
import elecciones.PartidoPolitico;
import elecciones.Simpatizante;
import elecciones.Votantes;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josemi
 */
public class Igelec extends javax.swing.JFrame {
    
    private ArrayList<FormacionPolitica> formacionesPoliticas = new ArrayList<>();
    private ArrayList<Militante> militantesAuxiliar;
    private ArrayList<Votantes> votantesAuxiliar;
    

    /**
     * Creates new form igelec
     */
    public Igelec() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameAñadirPartido = new javax.swing.JFrame();
        jButtonAñadirPP = new javax.swing.JButton();
        jLabelNombrePP = new javax.swing.JLabel();
        jTextFieldNombrePP = new javax.swing.JTextField();
        jLabelSiglasPP = new javax.swing.JLabel();
        jTextFieldSiglasPP = new javax.swing.JTextField();
        jLabelLogoPP = new javax.swing.JLabel();
        jTextFieldLogoPP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVotantesPP = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonAñadirSPartido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFrameAñadirSimpatizantePartido = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombreAñadirS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEdadAñadirS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldGeneroAñadirS = new javax.swing.JTextField();
        jTextFieldProfesionS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonAñadirSimpatizante = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSiglasS = new javax.swing.JTextField();
        Cargar = new javax.swing.JTabbedPane();
        TabPersonas = new javax.swing.JPanel();
        InfoPersonas = new javax.swing.JScrollPane();
        jTablePersonas = new javax.swing.JTable();
        añadirPersona = new javax.swing.JButton();
        borrarPersona = new javax.swing.JButton();
        importarPersona = new javax.swing.JButton();
        exportarPersona = new javax.swing.JButton();
        TabFP = new javax.swing.JPanel();
        InfoFormacionesPoliticas = new javax.swing.JScrollPane();
        jTableFormacionesPoliticas = new javax.swing.JTable();
        añadirPartido = new javax.swing.JButton();
        añadirCoalicion = new javax.swing.JButton();
        borrarFormacion = new javax.swing.JButton();
        importarPartido = new javax.swing.JButton();
        exportarPartido = new javax.swing.JButton();
        TabCircun = new javax.swing.JPanel();
        InfoCircunscripciones = new javax.swing.JScrollPane();
        jTableCircunscripcion = new javax.swing.JTable();
        añadirCircun = new javax.swing.JButton();
        borrarCircun = new javax.swing.JButton();
        importarCircun = new javax.swing.JButton();
        exportarCircun = new javax.swing.JButton();
        salidaTexto = new java.awt.TextArea();

        jFrameAñadirPartido.setMinimumSize(new java.awt.Dimension(911, 550));
        jFrameAñadirPartido.setPreferredSize(new java.awt.Dimension(911, 530));
        jFrameAñadirPartido.setResizable(false);
        jFrameAñadirPartido.setSize(new java.awt.Dimension(911, 530));

        jButtonAñadirPP.setText("Añadir Partido Politico");
        jButtonAñadirPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirPPActionPerformed(evt);
            }
        });

        jLabelNombrePP.setText("Nombre:");

        jLabelSiglasPP.setText("Siglas:");

        jLabelLogoPP.setText("Logo:");

        jButton1.setText("Cargar Militantes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableVotantesPP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Apellidos", "Edad", "Profesion", "Genero", "Siglas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVotantesPP);
        if (jTableVotantesPP.getColumnModel().getColumnCount() > 0) {
            jTableVotantesPP.getColumnModel().getColumn(0).setResizable(false);
            jTableVotantesPP.getColumnModel().getColumn(1).setResizable(false);
            jTableVotantesPP.getColumnModel().getColumn(2).setResizable(false);
            jTableVotantesPP.getColumnModel().getColumn(3).setResizable(false);
            jTableVotantesPP.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Votantes:");

        jButtonAñadirSPartido.setText("Añadir Simpatizante");
        jButtonAñadirSPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirSPartidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Datos Del Partido:");

        javax.swing.GroupLayout jFrameAñadirPartidoLayout = new javax.swing.GroupLayout(jFrameAñadirPartido.getContentPane());
        jFrameAñadirPartido.getContentPane().setLayout(jFrameAñadirPartidoLayout);
        jFrameAñadirPartidoLayout.setHorizontalGroup(
            jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameAñadirPartidoLayout.createSequentialGroup()
                .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameAñadirPartidoLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonAñadirSPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrameAñadirPartidoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButtonAñadirPP))))
                    .addGroup(jFrameAñadirPartidoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrameAñadirPartidoLayout.createSequentialGroup()
                                .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombrePP)
                                    .addComponent(jLabelSiglasPP)
                                    .addComponent(jLabelLogoPP))
                                .addGap(38, 38, 38)
                                .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNombrePP)
                                    .addComponent(jTextFieldSiglasPP)
                                    .addComponent(jTextFieldLogoPP, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jFrameAñadirPartidoLayout.setVerticalGroup(
            jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameAñadirPartidoLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFrameAñadirPartidoLayout.createSequentialGroup()
                        .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombrePP)
                            .addComponent(jTextFieldNombrePP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSiglasPP)
                            .addComponent(jTextFieldSiglasPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jFrameAñadirPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLogoPP)
                            .addComponent(jTextFieldLogoPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAñadirSPartido)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAñadirPP)))
                .addGap(25, 25, 25))
        );

        jLabel4.setText("Nombre y Apellidos:");

        jTextFieldNombreAñadirS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreAñadirSActionPerformed(evt);
            }
        });

        jLabel5.setText("Edad:");

        jLabel6.setText("Genero:");

        jLabel7.setText("Profesion:");

        jButtonAñadirSimpatizante.setText("Añadir Simpatizante");
        jButtonAñadirSimpatizante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirSimpatizanteActionPerformed(evt);
            }
        });

        jLabel2.setText("Siglas");

        javax.swing.GroupLayout jFrameAñadirSimpatizantePartidoLayout = new javax.swing.GroupLayout(jFrameAñadirSimpatizantePartido.getContentPane());
        jFrameAñadirSimpatizantePartido.getContentPane().setLayout(jFrameAñadirSimpatizantePartidoLayout);
        jFrameAñadirSimpatizantePartidoLayout.setHorizontalGroup(
            jFrameAñadirSimpatizantePartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameAñadirSimpatizantePartidoLayout.createSequentialGroup()
                .addGroup(jFrameAñadirSimpatizantePartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jFrameAñadirSimpatizantePartidoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jFrameAñadirSimpatizantePartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jFrameAñadirSimpatizantePartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreAñadirS)
                            .addComponent(jTextFieldEdadAñadirS)
                            .addComponent(jTextFieldGeneroAñadirS)
                            .addComponent(jTextFieldProfesionS)
                            .addComponent(jTextFieldSiglasS, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(jFrameAñadirSimpatizantePartidoLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButtonAñadirSimpatizante)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jFrameAñadirSimpatizantePartidoLayout.setVerticalGroup(
            jFrameAñadirSimpatizantePartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameAñadirSimpatizantePartidoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jFrameAñadirSimpatizantePartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNombreAñadirS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameAñadirSimpatizantePartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEdadAñadirS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameAñadirSimpatizantePartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldGeneroAñadirS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jFrameAñadirSimpatizantePartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldProfesionS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrameAñadirSimpatizantePartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSiglasS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButtonAñadirSimpatizante)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePersonas.setModel(new modelos.PersonaTableModel());
        InfoPersonas.setViewportView(jTablePersonas);

        añadirPersona.setText("Añadir");
        añadirPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirPersonaActionPerformed(evt);
            }
        });

        borrarPersona.setText("Eliminar seleccionados");

        importarPersona.setText("Importar");

        exportarPersona.setText("Exportar");

        javax.swing.GroupLayout TabPersonasLayout = new javax.swing.GroupLayout(TabPersonas);
        TabPersonas.setLayout(TabPersonasLayout);
        TabPersonasLayout.setHorizontalGroup(
            TabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabPersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrarPersona)
                    .addComponent(importarPersona)
                    .addComponent(exportarPersona)
                    .addComponent(añadirPersona))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabPersonasLayout.setVerticalGroup(
            TabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabPersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabPersonasLayout.createSequentialGroup()
                        .addComponent(añadirPersona)
                        .addGap(18, 18, 18)
                        .addComponent(borrarPersona)
                        .addGap(18, 18, 18)
                        .addComponent(importarPersona)
                        .addGap(18, 18, 18)
                        .addComponent(exportarPersona))
                    .addComponent(InfoPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Cargar.addTab("Personas", TabPersonas);

        jTableFormacionesPoliticas.setModel(new modelos.PartidoTableModel());
        InfoFormacionesPoliticas.setViewportView(jTableFormacionesPoliticas);
        if (jTableFormacionesPoliticas.getColumnModel().getColumnCount() > 0) {
            jTableFormacionesPoliticas.getColumnModel().getColumn(0).setResizable(false);
            jTableFormacionesPoliticas.getColumnModel().getColumn(1).setResizable(false);
        }

        añadirPartido.setText("Añadir Partido Político");
        añadirPartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirPartidoMouseClicked(evt);
            }
        });
        añadirPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirPartidoActionPerformed(evt);
            }
        });

        añadirCoalicion.setText("Crear Coalición");
        añadirCoalicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirCoalicionActionPerformed(evt);
            }
        });

        borrarFormacion.setText("Eliminar Seleccionados");

        importarPartido.setText("Importar Partido");

        exportarPartido.setText("Exportar Partido");

        javax.swing.GroupLayout TabFPLayout = new javax.swing.GroupLayout(TabFP);
        TabFP.setLayout(TabFPLayout);
        TabFPLayout.setHorizontalGroup(
            TabFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabFPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoFormacionesPoliticas, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TabFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(añadirCoalicion)
                    .addComponent(añadirPartido)
                    .addComponent(borrarFormacion)
                    .addComponent(importarPartido)
                    .addComponent(exportarPartido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabFPLayout.setVerticalGroup(
            TabFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabFPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabFPLayout.createSequentialGroup()
                        .addComponent(añadirPartido)
                        .addGap(18, 18, 18)
                        .addComponent(añadirCoalicion)
                        .addGap(18, 18, 18)
                        .addComponent(borrarFormacion)
                        .addGap(18, 18, 18)
                        .addComponent(importarPartido)
                        .addGap(18, 18, 18)
                        .addComponent(exportarPartido))
                    .addComponent(InfoFormacionesPoliticas, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Cargar.addTab("Formaciones Políticas", TabFP);

        jTableCircunscripcion.setModel(new modelos.CircunscripcionTableModel());
        InfoCircunscripciones.setViewportView(jTableCircunscripcion);

        añadirCircun.setText("Añadir");
        añadirCircun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirCircunActionPerformed(evt);
            }
        });

        borrarCircun.setText("Borrar");

        importarCircun.setText("Importar");

        exportarCircun.setText("Exportar");

        javax.swing.GroupLayout TabCircunLayout = new javax.swing.GroupLayout(TabCircun);
        TabCircun.setLayout(TabCircunLayout);
        TabCircunLayout.setHorizontalGroup(
            TabCircunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabCircunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoCircunscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TabCircunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrarCircun)
                    .addComponent(importarCircun)
                    .addComponent(exportarCircun)
                    .addComponent(añadirCircun))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        TabCircunLayout.setVerticalGroup(
            TabCircunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabCircunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabCircunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabCircunLayout.createSequentialGroup()
                        .addComponent(añadirCircun)
                        .addGap(18, 18, 18)
                        .addComponent(borrarCircun)
                        .addGap(18, 18, 18)
                        .addComponent(importarCircun)
                        .addGap(18, 18, 18)
                        .addComponent(exportarCircun))
                    .addComponent(InfoCircunscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Cargar.addTab("Circunscripciones", TabCircun);

        salidaTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        salidaTexto.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cargar, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salidaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salidaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );

        Cargar.getAccessibleContext().setAccessibleName("Pestañas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirPartidoActionPerformed
        // TODO add your handling code here:
        jFrameAñadirPartido.setLocationRelativeTo(null);
        jFrameAñadirPartido.setSize(400, 400);
        jFrameAñadirPartido.setVisible(true);
       
        /*
        DefaultTableModel modelo = (DefaultTableModel) jTableVotantesPP.getModel();
        while(modelo.getRowCount() > 0) modelo.removeRow(0);      */
        
        limpiarTabla(jTableVotantesPP);
        
        
        
    }//GEN-LAST:event_añadirPartidoActionPerformed

    private void añadirPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadirPersonaActionPerformed

    private void añadirCircunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirCircunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadirCircunActionPerformed

    private void añadirPartidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirPartidoMouseClicked
        //jPanelAñadirPartido.setVisible(true);
    }//GEN-LAST:event_añadirPartidoMouseClicked

    private void jButtonAñadirPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirPPActionPerformed
        // TODO add your handling code here:
        PartidoPolitico nuevoPartido = new PartidoPolitico(jTextFieldNombrePP.getText(), jTextFieldSiglasPP.getText(), jTextFieldLogoPP.getText());
        nuevoPartido.setMilitantes(militantesAuxiliar);
        nuevoPartido.setVotantes(votantesAuxiliar);

        formacionesPoliticas.add(nuevoPartido);
        
        //Rellena tabla formaciones politicas
        DefaultTableModel modelo = (DefaultTableModel) jTableFormacionesPoliticas.getModel();
        Object[] fila = new Object[]{nuevoPartido.getNombre(),nuevoPartido.getSiglas()};
        modelo.addRow(fila);
        
        
        //Resetea campos
        jFrameAñadirPartido.setVisible(false);
        jTextFieldNombrePP.setText("");
        jTextFieldLogoPP.setText("");
        jTextFieldSiglasPP.setText("");
        
        
        
        System.out.println(formacionesPoliticas.toString());
        
        
    }//GEN-LAST:event_jButtonAñadirPPActionPerformed

    private void añadirCoalicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirCoalicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadirCoalicionActionPerformed

    private void jButtonAñadirSimpatizanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirSimpatizanteActionPerformed
        // TODO add your handling code here:
        String nom = jTextFieldNombreAñadirS.getText();
        int edad = Integer.parseInt(jTextFieldEdadAñadirS.getText());
        String prof = jTextFieldProfesionS.getText();
        char g = jTextFieldGeneroAñadirS.getText().charAt(0);
        String siglas = jTextFieldSiglasS.getText();
        Simpatizante simpatizanteAuxiliar = new Simpatizante(nom,edad,prof,g,siglas);
        
        votantesAuxiliar.add(simpatizanteAuxiliar);
        limpiarTabla(jTableVotantesPP);
        
        DefaultTableModel modelo = (DefaultTableModel) jTableVotantesPP.getModel();
        for(Votantes i : votantesAuxiliar){
            Object[] fila = new Object[]{i.getNombreApellidos(),i.getEdad(),i.getProfesion(),i.getGenero(),i.getSiglasPartido()};
            modelo.addRow(fila);
        }
        
        
        
        jFrameAñadirSimpatizantePartido.setVisible(false);
        jTextFieldNombreAñadirS.setText("");
        jTextFieldEdadAñadirS.setText("");        
        jTextFieldProfesionS.setText("");
        jTextFieldGeneroAñadirS.setText("");
        jTextFieldSiglasS.setText("");
    }//GEN-LAST:event_jButtonAñadirSimpatizanteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int archivo = fileChooser.showOpenDialog(this); //Se abre la ventana para seleccionar archivo a cargar.
        if (archivo == JFileChooser.APPROVE_OPTION){
            File fichero = fileChooser.getSelectedFile(); //Se crea una variable con el fichero
            String entrada = fichero.getPath();//Se recoge la ruta del fichero
            
            
            try{
                militantesAuxiliar = new ArrayList<>();
                votantesAuxiliar = new ArrayList<>();
                BufferedReader inFile = new BufferedReader (new FileReader(entrada));
                String inputLine;
                
                while ((inputLine = inFile.readLine())!=null){
                    String[] AtributosMilitante = inputLine.split(":");
                    String nomApe = AtributosMilitante[0];
                    int edad = Integer.parseInt(AtributosMilitante[1]);
                    String prof = AtributosMilitante[2];
                    char gen = AtributosMilitante[3].charAt(0);
                    String siglas = AtributosMilitante[4];
                    double cuota = Double.parseDouble(AtributosMilitante[5]);
                    String carnet = AtributosMilitante[6];
                    
                    Militante m = new Militante(nomApe,edad,prof,gen,siglas,cuota,carnet);
                    militantesAuxiliar.add(m);    
        
            }
            }catch(FileNotFoundException e){
                e.printStackTrace();
                
                
            } catch (IOException ex) {
                Logger.getLogger(Igelec.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ArrayIndexOutOfBoundsException e2){
                e2.printStackTrace();
                System.out.println("Los datos del fichero no son validos");
                    
            }
            
        }
           for(Militante i: militantesAuxiliar){
            votantesAuxiliar.add(i);
        }
        
        DefaultTableModel modelo = (DefaultTableModel) jTableVotantesPP.getModel();
        for(Votantes i : votantesAuxiliar){
            Object[] fila = new Object[]{i.getNombreApellidos(),i.getEdad(),i.getProfesion(),i.getGenero(),i.getSiglasPartido()};
            modelo.addRow(fila);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNombreAñadirSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreAñadirSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreAñadirSActionPerformed

    private void jButtonAñadirSPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirSPartidoActionPerformed
        // TODO add your handling code here:
                jFrameAñadirSimpatizantePartido.setLocationRelativeTo(null);
        jFrameAñadirSimpatizantePartido.setSize(400, 400);
        jFrameAñadirSimpatizantePartido.setVisible(true);
        jTextFieldNombreAñadirS.setText("");
        jTextFieldEdadAñadirS.setText("");
        jTextFieldProfesionS.setText("");
        jTextFieldGeneroAñadirS.setText("");
        jTextFieldSiglasS.setText("");
    }//GEN-LAST:event_jButtonAñadirSPartidoActionPerformed

    //metodo para limpiar cualquier tabla
    public void limpiarTabla(JTable tabla){
         DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        while(modelo.getRowCount()>0)modelo.removeRow(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Igelec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Igelec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Igelec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Igelec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Igelec().setVisible(true);
            }
        });
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Cargar;
    private javax.swing.JScrollPane InfoCircunscripciones;
    private javax.swing.JScrollPane InfoFormacionesPoliticas;
    private javax.swing.JScrollPane InfoPersonas;
    private javax.swing.JPanel TabCircun;
    private javax.swing.JPanel TabFP;
    private javax.swing.JPanel TabPersonas;
    private javax.swing.JButton añadirCircun;
    private javax.swing.JButton añadirCoalicion;
    private javax.swing.JButton añadirPartido;
    private javax.swing.JButton añadirPersona;
    private javax.swing.JButton borrarCircun;
    private javax.swing.JButton borrarFormacion;
    private javax.swing.JButton borrarPersona;
    private javax.swing.JButton exportarCircun;
    private javax.swing.JButton exportarPartido;
    private javax.swing.JButton exportarPersona;
    private javax.swing.JButton importarCircun;
    private javax.swing.JButton importarPartido;
    private javax.swing.JButton importarPersona;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAñadirPP;
    private javax.swing.JButton jButtonAñadirSPartido;
    private javax.swing.JButton jButtonAñadirSimpatizante;
    private javax.swing.JFrame jFrameAñadirPartido;
    private javax.swing.JFrame jFrameAñadirSimpatizantePartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelLogoPP;
    private javax.swing.JLabel jLabelNombrePP;
    private javax.swing.JLabel jLabelSiglasPP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCircunscripcion;
    private javax.swing.JTable jTableFormacionesPoliticas;
    private javax.swing.JTable jTablePersonas;
    private javax.swing.JTable jTableVotantesPP;
    private javax.swing.JTextField jTextFieldEdadAñadirS;
    private javax.swing.JTextField jTextFieldGeneroAñadirS;
    private javax.swing.JTextField jTextFieldLogoPP;
    private javax.swing.JTextField jTextFieldNombreAñadirS;
    private javax.swing.JTextField jTextFieldNombrePP;
    private javax.swing.JTextField jTextFieldProfesionS;
    private javax.swing.JTextField jTextFieldSiglasPP;
    private javax.swing.JTextField jTextFieldSiglasS;
    private java.awt.TextArea salidaTexto;
    // End of variables declaration//GEN-END:variables

}
